### ISSUE TITLE
Import von zugehörigen Templates defekt?

### ISSUE THREAD

**Issue by ngdot** [fritzmg/contao-lazy-load-element#1]
Hi, erst einmal super coole Erweiterung!
Habe allerdings einen Fehler entdeckt.
Ich vermute, dass deine Erweiterung die Templates der einzubindenden Elementen nicht mit importiert. Ich habe z.B. eine Galerie über deine Erweiterung geladen, allerdings lädt er das hinterlegte Template nicht (welches das bearbeitete default ist). Gleiches Phänomen bei einem YouTube-Element, hier wird nur ein leerer HTML5 Player angezeigt, aber nicht der Contao eigene YouTube-Player. Bei HTML-Elementen funktioniert es problemlos.

**Comment by fritzmg** [comment]
Das mit den Galerien müsste ich testen, sollte aber eigentlich funktionieren. 

Wenn du mit dem "Contao eigenen Player" MediaElement.js meinst, dann ja, das funktioniert nicht - aber generell nicht, ohne eigene Vorkehrungen zu treffen. Die Player werden ja initialisiert, wenn die Seite fertig geladen wurde. Aber wenn du Lazy Load benutzt, wird das Element ja erst später geladen. 

Zu letzterem und wollte ich eigentlich noch einen Event Trigger einbauen, das ist in den bisherigen pre-releases noch nicht drin.

**Comment by ngdot** [comment]
Okay, macht Sinn. Aber das mit der Galerie verstehe ich dann nach wie vor nicht. Event Trigger klingt gut :) Bin gespannt.

**Comment by fritzmg** [comment]
Kann es sein dass dein Galerie Template in einem Theme Unterordner ist?

**Comment by fritzmg** [comment]
fixed in 0ad8a4353a8e4bd87952e5d5a8545ce1257420cc

**Comment by fritzmg** [comment]
In Version `0.3.0` gibt es jetzt außerdem das JavaScript event (siehe README).

**Comment by ngdot** [comment]
Danke, ja mein Template war bzw. ist in meinem Theme Unterordner. Mit Version 0.3.0 funktioniert nun das Template, bekomme allerdings ein paar Warnings von contao-haste und von TinyMceFontAwesome. Hier mal die Meldung:

> Recoverable error: Argument 3 passed to TinyMceFontAwesome\TinyMceFontAwesome::hookGetPageLayout() must be an instance of PageRegular, null given, called in /Applications/MAMP/htdocs/dumb/system/modules/lazy_load_element/classes/LazyLoadInterface.php on line 64 and defined in system/modules/TinyMceFontAwesome/classes/TinyMceFontAwesome.php on line 71
> #0 system/modules/TinyMceFontAwesome/classes/TinyMceFontAwesome.php(71): __error(4096, 'Argument 3 pass...', '/Applications/M...', 71, Array)
> #1 system/modules/lazy_load_element/classes/LazyLoadInterface.php(64): TinyMceFontAwesome\TinyMceFontAwesome->hookGetPageLayout(Object(Contao\PageModel), Object(Contao\LayoutModel), NULL)
> #2 composer/vendor/richardhj/contao-simple-ajax/src/SimpleAjax/SimpleAjax.php(133): LazyLoadInterface::loadElement()
> #3 composer/vendor/richardhj/contao-simple-ajax/src/SimpleAjax/SimpleAjax.php(100): SimpleAjax\SimpleAjax->runHooks()
> #4 SimpleAjaxFrontend.php(21): SimpleAjax\SimpleAjax->handle()
> #5 {main}
> 
> Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/dumb/system/helper/functions.php:65) in composer/vendor/codefog/contao-haste/library/Haste/Http/Response/Response.php on line 224
> #0 [internal function]: __error(2, 'Cannot modify h...', '/Applications/M...', 224, Array)
> #1 composer/vendor/codefog/contao-haste/library/Haste/Http/Response/Response.php(224): header_remove('Content-Length')
> #2 composer/vendor/codefog/contao-haste/library/Haste/Http/Response/Response.php(256): Haste\Http\Response\Response->prepare()
> #3 system/modules/lazy_load_element/classes/LazyLoadInterface.php(138): Haste\Http\Response\Response->send()
> #4 composer/vendor/richardhj/contao-simple-ajax/src/SimpleAjax/SimpleAjax.php(133): LazyLoadInterface::loadElement()
> #5 composer/vendor/richardhj/contao-simple-ajax/src/SimpleAjax/SimpleAjax.php(100): SimpleAjax\SimpleAjax->runHooks()
> #6 SimpleAjaxFrontend.php(21): SimpleAjax\SimpleAjax->handle()
> #7 {main}
> 
> Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/dumb/system/helper/functions.php:65) in composer/vendor/codefog/contao-haste/library/Haste/Http/Response/Response.php on line 224
> #0 [internal function]: __error(2, 'Cannot modify h...', '/Applications/M...', 224, Array)
> #1 composer/vendor/codefog/contao-haste/library/Haste/Http/Response/Response.php(224): header_remove('Content-Type')
> #2 composer/vendor/codefog/contao-haste/library/Haste/Http/Response/Response.php(256): Haste\Http\Response\Response->prepare()
> #3 system/modules/lazy_load_element/classes/LazyLoadInterface.php(138): Haste\Http\Response\Response->send()
> #4 composer/vendor/richardhj/contao-simple-ajax/src/SimpleAjax/SimpleAjax.php(133): LazyLoadInterface::loadElement()
> #5 composer/vendor/richardhj/contao-simple-ajax/src/SimpleAjax/SimpleAjax.php(100): SimpleAjax\SimpleAjax->runHooks()
> #6 SimpleAjaxFrontend.php(21): SimpleAjax\SimpleAjax->handle()
> #7 {main}

Muss ich mich an die Entwickler der eben genannten Erweiterungen wenden, oder hat deine Erweiterung was damit zutun?

**Comment by fritzmg** [comment]
Ah, da hab ich nicht gut genug getestet ;).

**Comment by ngdot** [comment]
Dafür bin ich ja da ;D

**Comment by fritzmg** [comment]
Kannst du mal den aktuellen master branch testen? Bzw. diese Änderung: https://github.com/fritzmg/contao-lazy-load-element/commit/845ae1536751ad5bd466b6af58f69c793c52c6f1

**Comment by ngdot** [comment]
Funzt!

**Comment by fritzmg** [comment]
@NicolasGoerlach übrigens Vorsicht beim Update auf Verison 1.0 - falls du das automatische reloading verwendest. Habe das auf Sekunden statt Millisekunden geändert, aber nicht extra eine `runonce.php` dafür gemacht ;)

**Comment by ngdot** [comment]
Danke für den Hinweis!
